spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: qcy96416218
  mvc:
    #http请求访问地址，请求非controller地址
    static-path-pattern: /**
#端口设置,默认为8080
server:
  port: 8080
#mybatis的包名别名设置
mybatis:
  type-aliases-package: com.mu.pojo
  configuration:
    map-underscore-to-camel-case: true
