spring:
  application:
    name: music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_c?allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    #http请求访问地址，请求非controller地址
    static-path-pattern: /**
  #响应的数据的序列化等，时间默认的序列话对象为data，对localdate等对象无效
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 8022
    #下面是默认值
    jedis:
      pool:
        max-active: 16 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0   # 连接池中的最小空闲连接
    password: 123456
#端口设置,默认为8080
server:
  port: 8080
#mybatis的包名别名设置
mybatis:
  type-aliases-package: com.mu.entities
  configuration:
    map-underscore-to-camel-case: true
#自定义路径设置
storage:
  rootPath: D:/static/
  userHead: User/head/
  defaultHead: f59619afdf2ff0f76ff3b63838f6d19a.jpeg
  staticResourcePath: http://localhost/static/
springfox:
  documentation:
    auto-startup: true
# 项目名称

########### 自定义swagger配置 ###########
# 是否开启swagger，开发环境打开，线上关闭
# 项目名称：enable
# 项目版本信息：application-version
# 项目描述信息：application-description
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 我的音乐项目
